RUNTIME_ERROR: Out of bounds error in 'a' at line number 2
